name: Daily YouTube Fetch

on:
  schedule:
    - cron: "0 11 * * *"  # Runs at 11 AM UTC (4 PM Karachi Time)
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-api-python-client pandas

      - name: Run YouTube Stats Script
        run: python stats.py

      - name: Commit and Push CSV
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add youtube_stats.csv
          git commit -m "Updated YouTube stats $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
